# Generated by Django 5.2.5 on 2025-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_booking_options_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='reservation_room_id_e0bdcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='reservation_status_ee4b50_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out_date',
            new_name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite')], default='single', max_length=20),
        ),
    ]
