# Generated by Django 5.2.5 on 2025-08-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_booking_reservation_room_id_e0bdcc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='occupants',
            field=models.PositiveIntegerField(default=1, help_text='Number of people lodging'),
        ),
    ]
